import '../src/styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: [],
};

export default function RootLayout({
  children,
  dashboard,
  login,
}: {
  children: React.ReactNode;
  login: React.ReactNode;
  dashboard: React.ReactNode;
}) {
  const isLoggedIn = true;
  const app = isLoggedIn ? dashboard : login;
  return (
    <html lang="en">
      <body>
        {children}
        {app}
      </body>
    </html>
  );
}
