import '@src/styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: [],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  login: React.ReactNode;
  dashboard: React.ReactNode;
}) {
  const isLoggedIn = true;
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
